export { usage } from './Tabs.demo.usage';
export { position } from './Tabs.demo.position';
export { pull } from './Tabs.demo.pull';
export { inverted } from './Tabs.demo.inverted';
export { placement } from './Tabs.demo.placement';
export { disabled } from './Tabs.demo.disabled';
export { colors } from './Tabs.demo.colors';
export { deactivate } from './Tabs.demo.deactivate';
export { keyboardActivation } from './Tabs.demo.keyboardActivation';
